location: .gitman
sources:
- name: libNEMA
  repo: https://github.com/mrpossoms/libNEMA
  rev: master
  link: ./external/libNEMA
- name: indicurses
  repo: https://github.com/mrpossoms/indicurses
  rev: master
  link: ./external/indicurses
- name: libKF
  repo: https://github.com/mrpossoms/libKF
  rev: master
  link: ./external/libKF
- name: linmath.h
  repo: https://github.com/mrpossoms/linmath.h
  rev: master
  link: ./external/linmath.h
- name: opt.h
  repo: https://github.com/mrpossoms/opt.h
  rev: master
  link: ./external/opt.h
